language: go

service:
  - docker

go:
  - 1.15.5

before_install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

script:
  - make lint test
  - docker build -t classik19881/simple_service .

deploy:
  provider: script
  script: bash .docker_push
  on:
    branch: master